// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHKDBrhztM4mgQcDSUfePr7IUMs1GM7Hg',
    appId: '1:754474234926:web:732cce3c9826e1d1c3dbbf',
    messagingSenderId: '754474234926',
    projectId: 'flutterfire-ui-codelab-f5805',
    authDomain: 'flutterfire-ui-codelab-f5805.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-f5805.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfub5C2AnGM8DEkF2qre774MERVvh_Qqg',
    appId: '1:754474234926:android:6cd863bbeaa0233dc3dbbf',
    messagingSenderId: '754474234926',
    projectId: 'flutterfire-ui-codelab-f5805',
    storageBucket: 'flutterfire-ui-codelab-f5805.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB58eR5_K_-ObT4S06PRN3Mgp_A7VQuznw',
    appId: '1:754474234926:ios:2a6dc734335cd39dc3dbbf',
    messagingSenderId: '754474234926',
    projectId: 'flutterfire-ui-codelab-f5805',
    storageBucket: 'flutterfire-ui-codelab-f5805.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB58eR5_K_-ObT4S06PRN3Mgp_A7VQuznw',
    appId: '1:754474234926:ios:2a6dc734335cd39dc3dbbf',
    messagingSenderId: '754474234926',
    projectId: 'flutterfire-ui-codelab-f5805',
    storageBucket: 'flutterfire-ui-codelab-f5805.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

}